index:
  path: /createClient
  controller: \App\Controller\SecurityController::AuthenticationAction

delete:
  path: /deleteClient
  controller: \App\Controller\SecurityController::RemoveAction

register_user:
  path: /login
  controller: \App\Controller\UserController::registerAction

fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
